### ISSUE TITLE
Move nginx-3scale container to latest released openresty

### ISSUE THREAD

**Issue by krish7919** [bigchaindb/nginx_3scale#3]
We are using a dns resolver in the `stream` block, which is supported in nginx but not in openresty.
Openresty usually lags behind by 1 version wrt nginx.

**Comment by ttmc** [comment]
According to the comments in `nginx.conf.template`, this issue is waiting for NGINX 1.11.3. For convenience, the changelogs of latest releases of OpenResty are listed at:

https://openresty.org/en/changes.html

**Comment by krish7919** [comment]
@ttmc: Last I checked, it was going to be at least a month for the release. The issue is here: openresty/openresty/issues/223

**Comment by ttmc** [comment]
I'm closing this issue here (in this repo) because we moved it over to bigchaindb/bigchaindb.
